#define MyAppName "Workflow Recorder"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "Workflow Recorder"
#define MyAppExeName "workflow-recorder.exe"
#define MyAppURL "https://github.com/gaozhi-ustc/computer-use"

[Setup]
AppId={{B7E4F2A1-3D5C-4E8A-9B1F-2C6D7E8F9A0B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={autopf}\WorkflowRecorder
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=..\dist
OutputBaseFilename=WorkflowRecorder-{#MyAppVersion}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\workflow-recorder.exe
UninstallFilesDir={app}\uninst

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "addtopath"; Description: "Add to system PATH (run from any terminal)"; GroupDescription: "System integration:"
Name: "installservice"; Description: "Install as Windows service (auto-start on boot)"; GroupDescription: "Service options:"; Flags: unchecked

[Files]
; PyInstaller output
Source: "..\dist\WorkflowRecorder\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Config templates
Source: "..\config.example.yaml"; DestDir: "{app}"; DestName: "config.example.yaml"; Flags: ignoreversion
Source: "..\model_config.example.json"; DestDir: "{app}"; DestName: "model_config.example.json"; Flags: ignoreversion

; model_config.json will be generated by [Code] during install
; config.yaml preserved across upgrades
Source: "..\config.example.yaml"; DestDir: "{app}"; DestName: "config.yaml"; Flags: onlyifdoesntexist uninsneveruninstall

[Dirs]
Name: "{app}\workflows"; Permissions: users-full
Name: "{app}\logs"; Permissions: users-full

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-c ""{app}\model_config.json"""; WorkingDir: "{app}"
Name: "{group}\Edit Configuration"; Filename: "notepad.exe"; Parameters: """{app}\model_config.json"""
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-c ""{app}\model_config.json"""; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "notepad.exe"; Parameters: """{app}\model_config.json"""; Description: "Review model configuration"; Flags: nowait postinstall skipifsilent unchecked

[UninstallRun]
Filename: "{app}\workflow-recorder-service.exe"; Parameters: "stop"; Flags: runhidden; RunOnceId: "StopSvc"
Filename: "{app}\workflow-recorder-service.exe"; Parameters: "remove"; Flags: runhidden; RunOnceId: "RemoveSvc"

[Code]
var
  ModelPage: TWizardPage;
  ModelCombo: TNewComboBox;
  ApiKeyEdit: TNewEdit;
  UrlLabel: TNewStaticText;
  UrlEdit: TNewEdit;

procedure ModelComboChange(Sender: TObject);
begin
  if ModelCombo.ItemIndex = 0 then
  begin
    UrlEdit.Text := 'https://api.aicodemirror.com/api/codex/backend-api/codex/v1';
  end
  else
  begin
    UrlEdit.Text := 'https://coding.dashscope.aliyuncs.com/v1';
  end;
end;

procedure InitializeWizard();
var
  Lbl: TNewStaticText;
begin
  ModelPage := CreateCustomPage(wpSelectTasks,
    'Model Configuration',
    'Choose the AI model backend and enter your API key.');

  { Model selection }
  Lbl := TNewStaticText.Create(ModelPage);
  Lbl.Parent := ModelPage.Surface;
  Lbl.Caption := 'AI Model:';
  Lbl.Top := 10;
  Lbl.Left := 0;

  ModelCombo := TNewComboBox.Create(ModelPage);
  ModelCombo.Parent := ModelPage.Surface;
  ModelCombo.Top := 30;
  ModelCombo.Left := 0;
  ModelCombo.Width := 400;
  ModelCombo.Style := csDropDownList;
  ModelCombo.Items.Add('GPT-4o (AiCodeMirror)');
  ModelCombo.Items.Add('Qwen3.5-Plus (Alibaba DashScope)');
  ModelCombo.ItemIndex := 0;
  ModelCombo.OnChange := @ModelComboChange;

  { API URL }
  UrlLabel := TNewStaticText.Create(ModelPage);
  UrlLabel.Parent := ModelPage.Surface;
  UrlLabel.Caption := 'API Base URL:';
  UrlLabel.Top := 75;
  UrlLabel.Left := 0;

  UrlEdit := TNewEdit.Create(ModelPage);
  UrlEdit.Parent := ModelPage.Surface;
  UrlEdit.Top := 95;
  UrlEdit.Left := 0;
  UrlEdit.Width := 400;
  UrlEdit.Text := 'https://api.aicodemirror.com/api/codex/backend-api/codex/v1';

  { API Key }
  Lbl := TNewStaticText.Create(ModelPage);
  Lbl.Parent := ModelPage.Surface;
  Lbl.Caption := 'API Key:';
  Lbl.Top := 140;
  Lbl.Left := 0;

  ApiKeyEdit := TNewEdit.Create(ModelPage);
  ApiKeyEdit.Parent := ModelPage.Surface;
  ApiKeyEdit.Top := 160;
  ApiKeyEdit.Left := 0;
  ApiKeyEdit.Width := 400;
  ApiKeyEdit.Text := '';

  Lbl := TNewStaticText.Create(ModelPage);
  Lbl.Parent := ModelPage.Surface;
  Lbl.Caption := 'You can change these settings later in model_config.json';
  Lbl.Top := 200;
  Lbl.Left := 0;
  Lbl.Font.Color := clGray;
end;

function GetModelName(): string;
begin
  if ModelCombo.ItemIndex = 0 then
    Result := 'gpt-4o'
  else
    Result := 'qwen3.5-plus';
end;

function GetPresetKey(): string;
begin
  if ModelCombo.ItemIndex = 0 then
    Result := 'gpt'
  else
    Result := 'qwen';
end;

procedure WriteModelConfig();
var
  Lines: TStringList;
  ConfigPath: string;
begin
  ConfigPath := ExpandConstant('{app}\model_config.json');

  { Don't overwrite if already exists }
  if FileExists(ConfigPath) then
    Exit;

  Lines := TStringList.Create;
  try
    Lines.Add('{');
    Lines.Add('  "model_presets": {');
    Lines.Add('    "gpt": {');
    Lines.Add('      "name": "GPT-4o (OpenAI / AiCodeMirror)",');
    Lines.Add('      "model": "gpt-4o",');
    Lines.Add('      "base_url": "https://api.aicodemirror.com/api/codex/backend-api/codex/v1",');
    Lines.Add('      "detail": "low",');
    Lines.Add('      "max_tokens": 1000,');
    Lines.Add('      "temperature": 0.1,');
    Lines.Add('      "rate_limit_rpm": 30');
    Lines.Add('    },');
    Lines.Add('    "qwen": {');
    Lines.Add('      "name": "Qwen3.5-Plus (Alibaba DashScope)",');
    Lines.Add('      "model": "qwen3.5-plus",');
    Lines.Add('      "base_url": "https://coding.dashscope.aliyuncs.com/v1",');
    Lines.Add('      "detail": "low",');
    Lines.Add('      "max_tokens": 1000,');
    Lines.Add('      "temperature": 0.1,');
    Lines.Add('      "rate_limit_rpm": 30');
    Lines.Add('    }');
    Lines.Add('  },');
    Lines.Add('  "active_preset": "' + GetPresetKey() + '",');
    Lines.Add('  "analysis": {');
    Lines.Add('    "openai_api_key": "' + ApiKeyEdit.Text + '",');
    Lines.Add('    "retry_attempts": 3,');
    Lines.Add('    "retry_backoff_base": 2.0');
    Lines.Add('  }');
    Lines.Add('}');
    Lines.SaveToFile(ConfigPath);
  finally
    Lines.Free;
  end;
end;

{ --- PATH and Service logic --- }

procedure AddToPath(Dir: string);
var
  Path: string;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path) then
    Path := '';
  if Pos(Uppercase(Dir), Uppercase(Path)) = 0 then
  begin
    if Path <> '' then Path := Path + ';';
    Path := Path + Dir;
    RegWriteStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path);
  end;
end;

procedure RemoveFromPath(Dir: string);
var
  Path, NewPath: string;
  P: Integer;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path) then exit;
  P := Pos(Uppercase(Dir), Uppercase(Path));
  if P > 0 then
  begin
    NewPath := Copy(Path, 1, P - 1) + Copy(Path, P + Length(Dir) + 1, MaxInt);
    if (Length(NewPath) > 0) and (NewPath[1] = ';') then
      NewPath := Copy(NewPath, 2, MaxInt);
    RegWriteStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', NewPath);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    { Write model_config.json based on user selections }
    WriteModelConfig();

    if WizardIsTaskSelected('addtopath') then
      AddToPath(ExpandConstant('{app}'));
    if WizardIsTaskSelected('installservice') then
    begin
      Exec(ExpandConstant('{app}\workflow-recorder-service.exe'), 'install',
           ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
      Exec(ExpandConstant('{app}\workflow-recorder-service.exe'), 'start',
           ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    RemoveFromPath(ExpandConstant('{app}'));
end;
