#define MyAppName "Workflow Recorder"
#define MyAppVersion "0.5.1"
#define MyAppPublisher "Workflow Recorder"
#define MyAppExeName "workflow-recorder.exe"
#define MyAppURL "https://github.com/gaozhi-ustc/computer-use"

[Setup]
AppId={{B7E4F2A1-3D5C-4E8A-9B1F-2C6D7E8F9A0B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={autopf}\WorkflowRecorder
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=..\dist
OutputBaseFilename=WorkflowRecorder-{#MyAppVersion}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\workflow-recorder.exe
UninstallFilesDir={app}\uninst

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "addtopath"; Description: "Add to system PATH (run from any terminal)"; GroupDescription: "System integration:"
Name: "installservice"; Description: "Install as Windows service (auto-start on boot)"; GroupDescription: "Service options:"; Flags: unchecked

[Files]
; PyInstaller output
Source: "..\dist\WorkflowRecorder\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Config templates
Source: "..\config.example.yaml"; DestDir: "{app}"; DestName: "config.example.yaml"; Flags: ignoreversion
Source: "..\model_config.example.json"; DestDir: "{app}"; DestName: "model_config.example.json"; Flags: ignoreversion

; model_config.json is generated by [Code] during install.
; If it already exists (upgrade case), leave it alone.

[Dirs]
Name: "{app}\workflows"; Permissions: users-full
Name: "{app}\logs"; Permissions: users-full

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-c ""{app}\model_config.json"""; WorkingDir: "{app}"
Name: "{group}\Edit Configuration"; Filename: "notepad.exe"; Parameters: """{app}\model_config.json"""
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Parameters: "-c ""{app}\model_config.json"""; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "notepad.exe"; Parameters: """{app}\model_config.json"""; Description: "Review model configuration"; Flags: nowait postinstall skipifsilent unchecked

[UninstallRun]
Filename: "{app}\workflow-recorder-service.exe"; Parameters: "stop"; Flags: runhidden; RunOnceId: "StopSvc"
Filename: "{app}\workflow-recorder-service.exe"; Parameters: "remove"; Flags: runhidden; RunOnceId: "RemoveSvc"

[Code]
var
  SetupPage: TWizardPage;
  EmployeeIdEdit: TNewEdit;
  ApiKeyEdit: TNewEdit;
  ServerUrlEdit: TNewEdit;

procedure InitializeWizard();
var
  Lbl: TNewStaticText;
  Hint: TNewStaticText;
begin
  SetupPage := CreateCustomPage(wpSelectTasks,
    'Workflow Recorder Configuration',
    'Enter your employee ID and DashScope (Bailian) API key. Both are required for the recorder to run. You can change them later in model_config.json.');

  { Employee ID — 32px gap between label bottom and edit top for DPI+CJK safety }
  Lbl := TNewStaticText.Create(SetupPage);
  Lbl.Parent := SetupPage.Surface;
  Lbl.Caption := 'Employee ID (员工工号):';
  Lbl.Top := 8;
  Lbl.Left := 0;
  Lbl.AutoSize := True;

  EmployeeIdEdit := TNewEdit.Create(SetupPage);
  EmployeeIdEdit.Parent := SetupPage.Surface;
  EmployeeIdEdit.Top := 40;
  EmployeeIdEdit.Left := 0;
  EmployeeIdEdit.Width := 400;
  EmployeeIdEdit.Text := '';

  { DashScope API key }
  Lbl := TNewStaticText.Create(SetupPage);
  Lbl.Parent := SetupPage.Surface;
  Lbl.Caption := 'DashScope API Key (百炼平台 sk-...):';
  Lbl.Top := 88;
  Lbl.Left := 0;
  Lbl.AutoSize := True;

  ApiKeyEdit := TNewEdit.Create(SetupPage);
  ApiKeyEdit.Parent := SetupPage.Surface;
  ApiKeyEdit.Top := 120;
  ApiKeyEdit.Left := 0;
  ApiKeyEdit.Width := 400;
  ApiKeyEdit.Text := '';

  { Server URL }
  Lbl := TNewStaticText.Create(SetupPage);
  Lbl.Parent := SetupPage.Surface;
  Lbl.Caption := 'Server URL (服务端地址):';
  Lbl.Top := 168;
  Lbl.Left := 0;
  Lbl.AutoSize := True;

  ServerUrlEdit := TNewEdit.Create(SetupPage);
  ServerUrlEdit.Parent := SetupPage.Surface;
  ServerUrlEdit.Top := 200;
  ServerUrlEdit.Left := 0;
  ServerUrlEdit.Width := 400;
  ServerUrlEdit.Text := 'http://localhost:8000';

  { Hint }
  Hint := TNewStaticText.Create(SetupPage);
  Hint.Parent := SetupPage.Surface;
  Hint.Caption :=
    'Model: Qwen3.5-Plus (via DashScope)' + #13#10 +
    'If you leave Employee ID or API Key blank, the recorder will' + #13#10 +
    'prompt you on first run.';
  Hint.Top := 248;
  Hint.Left := 0;
  Hint.Font.Color := clGray;
  Hint.AutoSize := True;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  { No hard validation — blank fields are OK; init_wizard.py will ask at first run. }
end;

{ Escape backslash and double-quote for embedding in JSON string literals }
function JsonEscape(S: string): string;
var
  Res: string;
  I: Integer;
  Ch: Char;
begin
  Res := '';
  for I := 1 to Length(S) do
  begin
    Ch := S[I];
    if Ch = '\' then
      Res := Res + '\\'
    else if Ch = '"' then
      Res := Res + '\"'
    else
      Res := Res + Ch;
  end;
  Result := Res;
end;

procedure PatchExistingConfig(ConfigPath: string);
var
  Content: AnsiString;
  S: string;
  ServerUrl: string;
  EmpId: string;
  ApiKey: string;
begin
  if not LoadStringFromFile(ConfigPath, Content) then Exit;
  S := String(Content);

  ServerUrl := JsonEscape(Trim(ServerUrlEdit.Text));
  EmpId := JsonEscape(Trim(EmployeeIdEdit.Text));
  ApiKey := JsonEscape(Trim(ApiKeyEdit.Text));

  { Always update server.enabled to true }
  StringChange(S, '"enabled": false', '"enabled": true');
  StringChange(S, '"enabled":false', '"enabled": true');

  { Update server.url from known defaults to user-provided value }
  StringChange(S, '"url": "http://127.0.0.1:8000"', '"url": "' + ServerUrl + '"');
  StringChange(S, '"url": "http://localhost:8000"', '"url": "' + ServerUrl + '"');

  { Fill empty employee_id if user provided one }
  if EmpId <> '' then
    StringChange(S, '"employee_id": ""', '"employee_id": "' + EmpId + '"');

  { Fill empty api_key if user provided one }
  if ApiKey <> '' then
    StringChange(S, '"openai_api_key": ""', '"openai_api_key": "' + ApiKey + '"');

  { v0.4.0: migrate known-default values that changed between versions.
    Only replaces OLD defaults — users who customized a non-default value
    keep their tuning. Matches both compact and spaced JSON formats. }

  { capture.interval_seconds: migrate known OLD defaults to new default (1s).
    Only replaces values that were the exact default of a prior version — a
    user who set a custom value like 2 or 5 keeps their tuning. }
  StringChange(S, '"interval_seconds": 15',  '"interval_seconds": 1');
  StringChange(S, '"interval_seconds":15',   '"interval_seconds": 1');
  StringChange(S, '"interval_seconds": 15.0','"interval_seconds": 1');
  StringChange(S, '"interval_seconds": 3',   '"interval_seconds": 1');
  StringChange(S, '"interval_seconds":3',    '"interval_seconds": 1');
  StringChange(S, '"interval_seconds": 3.0', '"interval_seconds": 1');

  { session.max_duration_seconds: 3600 -> 0 (unlimited by default since v0.3.3) }
  StringChange(S, '"max_duration_seconds": 3600',  '"max_duration_seconds": 0');
  StringChange(S, '"max_duration_seconds":3600',   '"max_duration_seconds": 0');
  StringChange(S, '"max_duration_seconds": 3600.0','"max_duration_seconds": 0');

  SaveStringToFile(ConfigPath, AnsiString(S), False);
end;

procedure WriteModelConfig();
var
  Lines: TStringList;
  ConfigPath: string;
  EmpId: string;
  ApiKey: string;
begin
  ConfigPath := ExpandConstant('{app}\model_config.json');

  { On upgrade: patch server.url + server.enabled, fill empty fields }
  if FileExists(ConfigPath) then
  begin
    PatchExistingConfig(ConfigPath);
    Exit;
  end;

  EmpId := JsonEscape(Trim(EmployeeIdEdit.Text));
  ApiKey := JsonEscape(Trim(ApiKeyEdit.Text));

  Lines := TStringList.Create;
  try
    Lines.Add('{');
    Lines.Add('  "employee_id": "' + EmpId + '",');
    Lines.Add('  "model_presets": {');
    Lines.Add('    "qwen": {');
    Lines.Add('      "name": "Qwen3.5-Plus (Alibaba DashScope)",');
    Lines.Add('      "model": "qwen3.5-plus",');
    Lines.Add('      "base_url": "https://coding.dashscope.aliyuncs.com/v1",');
    Lines.Add('      "openai_api_key": "' + ApiKey + '",');
    Lines.Add('      "detail": "low",');
    Lines.Add('      "max_tokens": 1000,');
    Lines.Add('      "temperature": 0.1,');
    Lines.Add('      "rate_limit_rpm": 30');
    Lines.Add('    }');
    Lines.Add('  },');
    Lines.Add('  "active_preset": "qwen",');
    Lines.Add('  "analysis": {');
    Lines.Add('    "retry_attempts": 3,');
    Lines.Add('    "retry_backoff_base": 2.0');
    Lines.Add('  },');
    Lines.Add('  "capture": {');
    Lines.Add('    "interval_seconds": 1');
    Lines.Add('  },');
    Lines.Add('  "server": {');
    Lines.Add('    "enabled": true,');
    Lines.Add('    "url": "' + JsonEscape(Trim(ServerUrlEdit.Text)) + '",');
    Lines.Add('    "api_key": "",');
    Lines.Add('    "buffer_path": "./logs/push_buffer.jsonl"');
    Lines.Add('  }');
    Lines.Add('}');
    Lines.SaveToFile(ConfigPath);
  finally
    Lines.Free;
  end;
end;

{ --- PATH and Service logic --- }

procedure AddToPath(Dir: string);
var
  Path: string;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path) then
    Path := '';
  if Pos(Uppercase(Dir), Uppercase(Path)) = 0 then
  begin
    if Path <> '' then Path := Path + ';';
    Path := Path + Dir;
    RegWriteStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path);
  end;
end;

procedure RemoveFromPath(Dir: string);
var
  Path, NewPath: string;
  P: Integer;
begin
  if not RegQueryStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', Path) then exit;
  P := Pos(Uppercase(Dir), Uppercase(Path));
  if P > 0 then
  begin
    NewPath := Copy(Path, 1, P - 1) + Copy(Path, P + Length(Dir) + 1, MaxInt);
    if (Length(NewPath) > 0) and (NewPath[1] = ';') then
      NewPath := Copy(NewPath, 2, MaxInt);
    RegWriteStringValue(HKLM, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', NewPath);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    { Write model_config.json based on user input on the custom page }
    WriteModelConfig();

    if WizardIsTaskSelected('addtopath') then
      AddToPath(ExpandConstant('{app}'));
    if WizardIsTaskSelected('installservice') then
    begin
      Exec(ExpandConstant('{app}\workflow-recorder-service.exe'), 'install',
           ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
      Exec(ExpandConstant('{app}\workflow-recorder-service.exe'), 'start',
           ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    RemoveFromPath(ExpandConstant('{app}'));
end;
